### ISSUE TITLE
Ant Colony - failujace testy

### ISSUE THREAD

**Issue by vbaaccess** [daft-academy/daftacademy-python4beginners-autumn2021#15]
Wykonuje sobie testy u siebie zgodnie z przykładem
```python
#  Przykład:
#  colony = Colony("MyColony")
#  worker = colony.spawn_ant("worker")
#  worker.name == "worker"
#  worker.colony == colony
#  colony.ants == {worker}
#  worker2 = colony.spawn_ant("worker2")
#  colony.ants == {worker, worker2}
print(40*'*', 'TESTy 3.6','Mrowisko', 40*'*')
colony = Colony("my-colony")
worker = colony.spawn_ant("worker")
print('Test1', 'worker.name ==', worker.name)    #worker.name == "worker"
print('Test2', 'worker.colony ==', worker.colony)#worker.colony == colony
print('Test3', 'colony.ants ==', colony.ants)    #colony.ants == {worker}
worker2 = colony.spawn_ant("worker2")
print('Test4', 'colony.ants ==', colony.ants)    #colony.ants == {worker, worker2}
```
i niby wszystko wygląd ok
```
Test1 worker.name == worker
Test2 worker.colony == my-colony
Test3 colony.ants == {'worker'}
Test4 colony.ants == {'worker2', 'worker'}
```
ale RUN TEST z codingrooms zwraca mi błąd:

```
F..FF
======================================================================
FAIL: test_ant_spawning (coding_rooms_unit_tests.TestAntColony)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usercode/coding_rooms_unit_tests.py", line 19, in test_ant_spawning
    self.assertIs(worker.colony, colony)
AssertionError: 'my-colony' is not <task6.Colony object at 0x7fbb5a566940>

======================================================================
FAIL: test_multiple_ants (coding_rooms_unit_tests.TestAntColony)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usercode/coding_rooms_unit_tests.py", line 47, in test_multiple_ants
    self.assertIs(worker.colony, colony)
AssertionError: 'my-colony' is not <task6.Colony object at 0x7fbb5a5668e0>

======================================================================
FAIL: test_multiple_colonies (coding_rooms_unit_tests.TestAntColony)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usercode/coding_rooms_unit_tests.py", line 27, in test_multiple_colonies
    self.assertIs(alpha_worker.colony, colony_alpha)
AssertionError: 'alpha' is not <task6.Colony object at 0x7fbb5a566970>
```

z tego co rozumie to operujemy Obiektach klasy (klasy kolony i Ant) czyli na instancjach utworzonych mrowisk i mrówek
...   nie rozumiem z tych komunikatów o co chodzi, brakuje obiektu w pamięci ??

**Comment by krwiozercza-szynszyla** [comment]
dopisz na końcu swoich testów linijkę:
```
assert colony.ants == {worker, worker2}
```
jeśli zobaczysz błąd to znaczy, że `ants` nie zawiera zbioru mrówek. Strzelam, że są tam ich nazwy patrząc po treści issue

**Comment by StanislavRuduka** [comment]
@krwiozercza-szynszyla u mnie wszystko niby sie zgadza (porownuje objects a nie stringi) i tak testy sie wala w Coding Rooms a przechodza localnie. Ponizej kod, resultat, i blad z Coding Rooms.

```
class Ant:
    name: str
    colony: object

    def __init__(self, name, Colony):
        self.name = name
        self.colony = Colony
        Colony.ants.add(self)


class Colony:
    ants = set()
    name: str

    def __init__(self, name):
        self.name = name

    def spawn_ant(self, name):
        return Ant(name, self)


colony = Colony("MyColony")
worker = colony.spawn_ant("worker")

print(worker.name == "worker")
print(worker.colony == colony)
print(colony.ants == {worker})

worker2 = colony.spawn_ant("worker2")
print(colony.ants == {worker, worker2})
```
```

True
True
True
True

Process finished with exit code 0

```
```
..FFF
======================================================================
FAIL: test_empty_colony (coding_rooms_unit_tests.TestAntColony)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usercode/coding_rooms_unit_tests.py", line 13, in test_empty_colony
    self.assertEqual(colony.ants, set())
AssertionError: Items in the first set but not the second:
<task6.Ant object at 0x7fcdd4b46a30>

======================================================================
FAIL: test_multiple_ants (coding_rooms_unit_tests.TestAntColony)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usercode/coding_rooms_unit_tests.py", line 38, in test_multiple_ants
    self.assertEqual(colony.ants, set())
AssertionError: Items in the first set but not the second:
<task6.Ant object at 0x7fcdd4b46a30>

======================================================================
FAIL: test_multiple_colonies (coding_rooms_unit_tests.TestAntColony)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usercode/coding_rooms_unit_tests.py", line 28, in test_multiple_colonies
    self.assertEqual(colony_alpha.ants, {alpha_worker})
AssertionError: Items in the first set but not the second:
<task6.Ant object at 0x7fcdd4b46a30>

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=3)

```

**Comment by Kjablono** [comment]
@StanislavRuduka 
w Twoim rozwiązaniu pola `name` oraz `colony` są atrybutami klasy `Ant`, a nie instancji tej klasy. Analogiczna sytuacja w przypadku klasy `Colony`, ponadto do inicjalizatora klasy `Ant` przekazujesz parametr `Colony`, który prawdopodobnie w tym miejscu jest referencją do instancji klasy `Colony` , a nie klasą `Colony` (klasą jako obiekt - nazwa lokalnie przesłania nazwę klasy) co może prowadzić do jakichś dziwnych zachowań kodu

**Comment by krwiozercza-szynszyla** [comment]
@StanislavRuduka lokalnie tez nie dziala jak powinno:
```
>>> colony = Colony("MyColony")
>>> worker = colony.spawn_ant("worker")
>>> worker2 = colony.spawn_ant("worker2")
>>> colony2 = Colony("MyColony2")
>>> colony2.ants
{<__main__.Ant object at 0x7f3cb30e2f10>, <__main__.Ant object at 0x7f3cb30e2e50>}
```
