### ISSUE TITLE
list_updater - dziala lokalnie ale nie przechodzi testow

### ISSUE THREAD

**Issue by StanislavRuduka** [daft-academy/daftacademy-python4beginners-autumn2021#7]
Hej, 

Dostaje blad i nie kumam skad pohodzi, jak ranuje z tym samym input u siebie w PyCharmie, dostaje to co powinnem.

**Moj kod:** 
```
def list_updater(*argv, collection = []):
    if collection == None:
        collection = []
    for i in argv:
        collection.append(i)
    return collection
```
**Moj Blad:**

```
======================================================================
FAIL: test_multiple_cases (coding_rooms_unit_tests.TestListUpdater) (args=('test', 'test', 'test'), collection=None)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usercode/coding_rooms_unit_tests.py", line 17, in test_multiple_cases
    self._single_test(args, collection, expected_result)
  File "/usercode/coding_rooms_unit_tests.py", line 27, in _single_test
    self.assertEqual(result, expected_result)
AssertionError: Lists differ: [1, 2, 3, 'test', 'test', 'test'] != ['test', 'test', 'test']

First differing element 0:
1
'test'

First list contains 3 additional elements.
First extra element 3:
'test'

- [1, 2, 3, 'test', 'test', 'test']
?  ---------

+ ['test', 'test', 'test']

======================================================================
FAIL: test_multiple_cases (coding_rooms_unit_tests.TestListUpdater) (args=(), collection=None)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usercode/coding_rooms_unit_tests.py", line 17, in test_multiple_cases
    self._single_test(args, collection, expected_result)
  File "/usercode/coding_rooms_unit_tests.py", line 27, in _single_test
    self.assertEqual(result, expected_result)
AssertionError: Lists differ: [1, 2, 3, 'test', 'test', 'test'] != []

First list contains 6 additional elements.
First extra element 0:
1

- [1, 2, 3, 'test', 'test', 'test']
+ []

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (failures=2)
```

**Comment by krwiozercza-szynszyla** [comment]
@StanislavRuduka 
- Przeczytaj to: https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks
- Poprawnie sformatuj tresci tego issue

**Comment by StanislavRuduka** [comment]
dodalem ''' na kod, mam nadzieje ze teraz jest git

**Comment by krwiozercza-szynszyla** [comment]
```
>>> def list_updater(*argv, collection = []):
...     if collection == None:
...         collection = []
...     for i in argv:
...         collection.append(i)
...     return collection
... 
>>> list_updater(1, 2, 3)
[1, 2, 3]
>>> list_updater('test', 'test', 'test')
[1, 2, 3, 'test', 'test', 'test']
```

Przy wielokrotnym wywoływaniu funkcji wynik jest niepoprawny. Powinno być:

```
>>> list_updater(1, 2, 3)
[1, 2, 3]
>>> list_updater('test', 'test', 'test')
['test', 'test', 'test']
```
