### ISSUE TITLE
list_updater - wszystkie testy lokalnie działają, jeden daje sprzeczny output

### ISSUE THREAD

**Issue by Sharrix** [daft-academy/daftacademy-python4beginners-autumn2021#9]
```
def list_updater(*args, collection = None, **kwargs):
    output = []
    if args:
        for arg in args:
            if collection:
                collection.append(arg)
                output = collection
            else:
                output.append(arg)  
    elif kwargs:
        for key, value in kwargs.items():
            if collection:
                for i in value:
                    collection.append(i)
                output = collection
            else:
                for i in value:
                    output.append(i)
    return output
```
Lokalnie:
```
list_updater(1, 2, 3) = [1, 2, 3]
list_updater(1, 2, 3, collection=[5]) = [5, 1, 2, 3]
list_updater(args=(1, 2, 3), collection=None) = [1, 2, 3]
list_updater(args=('a', 'b', 'c'), collection=[1, 2]) = [1, 2, 'a', 'b', 'c']
list_updater(args=('test', 'test', 'test'), collection=None) = ['test', 'test', 'test']      
list_updater(args=(), collection=[1, 2, 3, 11]) = [1, 2, 3, 11]
list_updater(args=(), collection=None) = []
```
W Cooding rooms wysypuje się:
```
======================================================================
FAIL: test_multiple_cases (coding_rooms_unit_tests.TestListUpdater) (args=(), collection=[1, 2, 3, 11])
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usercode/coding_rooms_unit_tests.py", line 17, in test_multiple_cases
    self._single_test(args, collection, expected_result)
  File "/usercode/coding_rooms_unit_tests.py", line 27, in _single_test
    self.assertEqual(result, expected_result)
AssertionError: Lists differ: [] != [1, 2, 3, 11]

Second list contains 4 additional elements.
First extra element 0:
1

- []
+ [1, 2, 3, 11]
```

**Comment by krwiozercza-szynszyla** [comment]
> wszystkie testy lokalnie działają

Nie działają:

```
>>> def list_updater(*args, collection = None, **kwargs):
...     output = []
...     if args:
...         for arg in args:
...             if collection:
...                 collection.append(arg)
...                 output = collection
...             else:
...                 output.append(arg)  
...     elif kwargs:
...         for key, value in kwargs.items():
...             if collection:
...                 for i in value:
...                     collection.append(i)
...                 output = collection
...             else:
...                 for i in value:
...                     output.append(i)
...     return output
... 
>>> list_updater(collection=[1, 2, 3, 11])
[]
>>> list_updater(args=(), collection=[1, 2, 3, 11])
[1, 2, 3, 11]

```

1. Przechwytywanie `**kwargs` jest w tym zadaniu zbędne
2. Funkcja w przypadkach testowych nie jest wywoływana z wykorzystaniem `args=(...)`. Wywołanie `list_updater(args=('test', 'test', 'test'), collection=None)` powinno wyglądać tak: `list_updater('test', 'test', 'test', collection=None)`

**Comment by Sharrix** [comment]
czy poniżej wypluwa coś niepoprawnie?
![image](https://user-images.githubusercontent.com/62251687/142770909-21449f90-c0c9-428d-930c-7d2fb99f1f64.png)

1. Przechwytywanie **kwargs jest w tym zadaniu zbędne
2. Funkcja w przypadkach testowych nie jest wywoływana z wykorzystaniem args=(...). Wywołanie list_updater(args=('test', 'test', 'test'), collection=None) powinno wyglądać tak: list_updater('test', 'test', 'test', collection=None)


Nie rozumiem pdp 2.
list_updater(args=('test', 'test', 'test'), collection=None) pobiera args=('test', 'test', 'test') jako kwargs

**Comment by krwiozercza-szynszyla** [comment]
Nie wklejaj screenów, skopiuj treść/kod który chcesz pokazać i wklej go z odpowiednim formatowaniem tak jak w opisie issue.

Jeśli chodzi o drugi przykład to dla wywołań:

```
list_updater(1, 2, 3)
list_updater(1, 2, 3, collection=[5])
list_updater(collection=[5])
list_updater(collection=[1, 2, 3, 11])
```
Twoja poprawiona implementacja działa poprawnie.

Co do pozostałych 5 wywołań z przykładu nie jestem w stanie stwierdzić bo zadanie tego nie definiowało.

```
# Uzupełnij funkcję `list_updater` tak, aby przyjmowała
# dowolną ilość parametrów pozycyjnych i jeden opcjonalny `keyword`
# o nazwie `collection`.
```
Treść nie wspomina o argumencie typu "keyword" i nazwie `args` który z jakiegoś powodu starasz się obsłużyć.
